version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: junior_db
    environment:
      POSTGRES_USER: kristis
      POSTGRES_PASSWORD: kristis
      POSTGRES_DB: statement_db
    ports:
      - "5431:5432"
    restart: always
    networks:
      - app-network

  api:
    build: .  # Use Dockerfile
    container_name: junior_api
    depends_on:
      - db  # Start db first
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/statement_db
      SPRING_DATASOURCE_USERNAME: kristis
      SPRING_DATASOURCE_PASSWORD: kristis
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge